CREATE TABLE about (
  id SERIAL PRIMARY KEY,
  heading VARCHAR(100) NOT NULL,
  subtitle VARCHAR(255),
  content TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);